version: "3.8"

services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:stable
    ports:
      - "4566:4566"
      -
    environment:
      - SERVICES=s3
      - DEBUG=0
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
