name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform-build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start docker service of LocalStack
        run: docker-compose up -d

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Create Terraform plan
        run: terraform plan -out=plan

      - name: Apply Terraform plan
        if: github.event_name == 'push'
        run: terraform apply -auto-approve plan

      - name: Stop LocalStack
        if: always()
        run: docker-compose down